module.exports = {
  COMMUNITY_CHAT:"COMMUNITY_CHAT",
  USER_CONNECTED:"USER_CONNECTED",
  MESSAGE_RECIEVED:"MESSAGE_RECIEVED",
  MESSAGE_SENT:"MESSAGE_SENT",
  USER_DISCONNECT:"USER_DISCONNECT",
  USER_TYPING:"USER_TYPING",
  VERIFY_USER:"VERIFY_USER",
  LOGOUT:"LOGOUT",
  USER_INPUT:"USER_INPUT",
  GAME_UPDATE:"GAME_UPDATE"
}
